spring:
  application:
    name: FeedFocusBackend

  data:
    mongodb:
      uri: ${MONGO_URI}

server:
  port: ${PORT:8080}

frontend:
  url: ${FRONTEND_URL}

jwt:
  secret: ${JWT_SECRET}

rss:
  feeds:
    india:
      - https://www.theguardian.com/world/india/rss
      - https://www.sebi.gov.in/sebirss.xml
      - https://timesofindia.indiatimes.com/rssfeedstopstories.cms
      - https://www.thehindu.com/feeder/default.rss
      - https://feeds.feedburner.com/ndtvnews-top-stories
      - https://www.dnaindia.com/feeds/india.xml
      - https://www.freepressjournal.in/stories.rss
      - https://www.deccanchronicle.com/rss_feed/
      - http://feeds.feedburner.com/ScrollinArticles.rss
      - https://www.thehindubusinessline.com/feeder/default.rss
      - http://feeds.feedburner.com/techgenyz
      - https://feeds.feedburner.com/opindia
      - https://prod-qt-images.s3.amazonaws.com/production/swarajya/feed.xml
      - https://www.newindianexpress.com/Nation/rssfeed/?id=170&getXmlFeed=true
      - https://www.livemint.com/rss/news

    us:
      - https://rss.nytimes.com/services/xml/rss/nyt/US.xml
      - https://feeds.a.dj.com/rss/RSSWSJD.xml
      - https://www.npr.org/rss/rss.php?id=1001
      - https://www.cnbc.com/id/100003114/device/rss/rss.html
      - https://feeds.foxnews.com/foxnews/national

    uk:
      - https://www.theguardian.com/uk/rss
      - https://feeds.bbci.co.uk/news/uk/rss.xml
      - https://www.independent.co.uk/news/uk/rss
      - https://www.gbnews.com/feeds/news.rss
      - https://www.standard.co.uk/news/uk/rss
      - https://www.scotsman.com/news/rss

    general:
      - https://www.cnbc.com/id/100727362/device/rss/rss.html
      - https://rss.nytimes.com/services/xml/rss/nyt/World.xml
      - https://www.theguardian.com/world/rss
      - https://www.yahoo.com/news/rss
      - https://feeds.bbci.co.uk/news/world/rss.xml
      - https://www.aljazeera.com/xml/rss/all.xml
      - https://www.euronews.com/rss?level=theme&name=news
      - https://www.npr.org/rss/rss.php?id=1004
      - https://www.wired.com/feed/rss

    sports:
      - https://www.theguardian.com/sport/cricket/rss
      - https://rss.acast.com/cricket-unfiltered
      - https://www.spreaker.com/show/3387348/episodes/feed
      - https://www.firstpost.com/commonfeeds/v1/mfp/rss/sports.xml
      - https://www.espncricinfo.com/rss/content/story/feeds/0.xml
      - https://www.soccernews.com/feed
      - https://www.espn.com/espn/rss/news
      - https://www.skysports.com/rss/12040

    business:
      - https://www.investing.com/rss/news.rss
      - https://seekingalpha.com/market_currents.xml
      - https://www.forbes.com/business/feed/
      - https://fortune.com/feed
      - http://feeds.harvardbusiness.org/harvardbusiness/ideacast
      - https://feeds.feedburner.com/Mixergy-main-podcast
      - https://tim.blog/feed/
      - https://www.cnbc.com/id/100003114/device/rss/rss.html
      - https://finance.yahoo.com/news/rssindex
      - https://www.businessinsider.com/rss
      - https://www.economist.com/latest/rss.xml

    food:
      - https://www.101cookbooks.com/feed
      - https://www.davidlebovitz.com/feed/
      - http://feeds.feedburner.com/food52-TheAandMBlog
      - https://greenkitchenstories.com/feed/
      - https://www.howsweeteats.com/feed/
      - http://joythebaker.com/feed/
      - https://www.thekitchn.com/main.rss
      - https://www.loveandoliveoil.com/feed
      - https://rss.nytimes.com/services/xml/rss/nyt/DiningandWine.xml
      - https://www.bonappetit.com/feed/rss

    technology:
      - http://feeds.arstechnica.com/arstechnica/index
      - https://www.cnet.com/rss/news/
      - https://gizmodo.com/rss
      - https://news.ycombinator.com/rss
      - https://lifehacker.com/rss
      - http://feeds.mashable.com/Mashable
      - https://www.theverge.com/rss/index.xml
      - https://rss.nytimes.com/services/xml/rss/nyt/Technology.xml
      - https://www.engadget.com/rss.xml

    entertainment:
      - https://www.theguardian.com/uk/culture/rss
      - https://www.indiewire.com/feed
      - https://variety.com/feed/
      - https://www.koimoi.com/feed/
      - https://www.musicbusinessworldwide.com/feed/
      - https://edm.com/.rss/full/
      - http://feeds.feedburner.com/metalinjection
      - http://songexploder.net/feed
      - https://www.vanityfair.com/feed/rss
      - https://www.rollingstone.com/music/music-news/feed/
      - https://www.billboard.com/feed/

    science:
      - http://rss.sciam.com/sciam/60secsciencepodcast
      - https://www.nature.com/nature.rss
      - https://phys.org/rss-feed/
      - https://feeds.npr.org/510308/podcast.xml
      - https://feeds.npr.org/510307/podcast.xml
      - https://rss.nytimes.com/services/xml/rss/nyt/Science.xml
      - https://www.wired.com/feed/category/science/latest/rss
      - https://www.theguardian.com/science/rss
      - https://www.sciencemag.org/rss/news_current.xml
      - https://www.newscientist.com/feed/home/

    travel:
      - https://www.atlasobscura.com/feeds/latest
      - https://www.livelifetravel.world/feed/
      - https://rss.nytimes.com/services/xml/rss/nyt/Travel.xml
      - https://www.nomadicmatt.com/travel-blog/feed/
      - https://www.theguardian.com/uk/travel/rss

    fashion:
      - https://www.elle.com/rss/fashion.xml/
      - https://www.theguardian.com/fashion/rss
      - https://www.fashionbeans.com/rss-feed/?category=fashion
      - https://fashionista.com/.rss/excerpt/
      - https://rss.nytimes.com/services/xml/rss/nyt/FashionandStyle.xml
      - https://www.popsugar.com/fashion/feed
      - https://www.refinery29.com/fashion/rss.xml
      - https://www.whowhatwear.com/rss
      - https://www.vogue.com/feed/rss

    history:
      - https://feeds.megaphone.fm/ESP5765452710
      - https://feeds.feedburner.com/dancarlin/history?format=xml
      - https://www.historyisnowmagazine.com/blog?format=RSS
      - https://www.thehistoryreader.com/feed/
      - https://feeds.npr.org/510333/podcast.xml
      - http://feeds.thememorypalace.us/thememorypalace

    automotive:
      - https://www.autocarindia.com/RSS/rss.ashx?type=all_bikes
      - https://www.autocarindia.com/RSS/rss.ashx?type=all_cars
      - https://www.autocarindia.com/RSS/rss.ashx?type=News
      - https://www.autocar.co.uk/rss
      - https://feeds.feedburner.com/BmwBlog
      - https://www.bikeexif.com/feed
      - https://www.carbodydesign.com/feed/
      - https://www.carscoops.com/feed/

    health:
      - https://www.npr.org/rss/rss.php?id=1019
      - https://www.theguardian.com/society/health/rss
      - https://rss.nytimes.com/services/xml/rss/nyt/Health.xml
      - https://feeds.feedburner.com/psychcentral

    politics:
      - https://www.indiatoday.in/rss/1206497
      - https://www.opindia.com/feed/
      - https://swarajyamag.com/feed
      - https://www.firstpost.com/commonfeeds/v1/mfp/rss/politics.xml
      - https://www.nationalheraldindia.com/stories.rss?section=politics
      - https://rss.nytimes.com/services/xml/rss/nyt/Politics.xml
      - https://feeds.bbci.co.uk/news/politics/rss.xml
      - https://www.aljazeera.com/xml/rss/all.xml
      - https://www.theguardian.com/politics/rss
      - https://thehill.com/rss/syndicator/19110